name: base
channels:
- conda-forge
dependencies:
- altair==4.2.2
- annotated-types
- appnope
- argcomplete
- asttokens
- attrs
- aws-c-auth
- aws-c-cal
- aws-c-common
- aws-c-compression
- aws-c-event-stream
- aws-c-http
- aws-c-io
- aws-c-mqtt
- aws-c-s3
- aws-c-sdkutils
- aws-checksums
- aws-crt-cpp
- aws-sdk-cpp
- azure-core-cpp
- azure-identity-cpp
- azure-storage-blobs-cpp
- azure-storage-common-cpp
- azure-storage-files-datalake-cpp
- black
- blinker
- brotli-python
- bzip2
- c-ares
- ca-certificates
- cachetools
- certifi
- cffi
- charset-normalizer
- click
- colorama
- comm
- cpp-expected
- debugpy
- decorator
- exceptiongroup
- executing
- fmt
- freetype
- gflags
- gitdb
- gitpython
- glog
- h2
- hpack
- hyperframe
- icu
- idna
- importlib-metadata
- importlib_resources
- ipykernel
- ipython
- ipywidgets
- jedi
- jinja2
- jsonschema
- jsonschema-specifications
- jupyter_client
- jupyter_core
- jupyterlab_widgets
- krb5
- lcms2
- lerc
- libabseil
- libarchive
- libarrow
- libarrow-acero
- libarrow-dataset
- libarrow-substrait
- libblas
- libbrotlicommon
- libbrotlidec
- libbrotlienc
- libcblas
- libcrc32c
- libcurl
- libcxx
- libdeflate
- libedit
- libev
- libevent
- libexpat
- libffi
- libgfortran
- libgfortran5
- libgoogle-cloud
- libgoogle-cloud-storage
- libgrpc
- libiconv
- libjpeg-turbo
- liblapack
- libmamba
- libnghttp2
- libopenblas
- libparquet
- libpng
- libprotobuf
- libre2-11
- libsodium
- libsolv
- libsqlite
- libssh2
- libthrift
- libtiff
- libutf8proc
- libwebp-base
- libxcb
- libxml2
- libzlib
- llvm-openmp
- loguru
- lz4-c
- lzo
- mamba
- markdown-it-py
- markupsafe
- matplotlib-inline
- mdurl
- mypy_extensions
- narwhals
- ncurses
- nest-asyncio
- nlohmann_json
- numpy
- openjpeg
- openssl
- orc
- packaging
- pandas
- parso
- pathspec
- pexpect
- pickleshare
- pillow
- pip
- pipx
- pkgutil-resolve-name
- platformdirs
- prompt-toolkit
- protobuf
- psutil
- pthread-stubs
- ptyprocess
- pure_eval
- pyarrow
- pyarrow-core
- pycparser
- pydantic
- pydantic-core
- pydeck
- pygments
- pysocks
- python
- python-dateutil
- python-dotenv
- python-tzdata
- python_abi
- pytz
- pyyaml
- pyzmq
- re2
- readline
- referencing
- reproc
- reproc-cpp
- requests
- rich
- rpds-py
- setuptools
- shellingham
- simdjson
- six
- smmap
- snappy
- spdlog
- stack_data
- streamlit
- tenacity
- tk
- toml
- tomli
- tornado
- traitlets
- typer
- typer-slim
- typer-slim-standard
- typing
- typing-extensions
- typing_extensions
- tzdata
- tzlocal
- urllib3
- userpath
- validators
- watchdog
- wcwidth
- wheel
- widgetsnbextension
- xorg-libxau
- xorg-libxdmcp
- xz
- yaml
- yaml-cpp
- zeromq
- zipp
- zstandard
- zstd

