name: debrieftreepy
channels:
  - conda-forge
  - defaults
dependencies:
  - mamba
  - streamlit
  - ca-certificates
  - certifi
  - openssl
  - pydantic
  - black
  - loguru
  - typer
  - pipx
  - python-dotenv
  - ipython

