name: debriefmin
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=5.4.1
  - appnope=0.1.4
  - asttokens=2.4.1
  - attrs=24.2.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.0
  - aws-c-common=0.9.31
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.0
  - aws-c-io=0.15.0
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.0
  - aws-c-sdkutils=0.2.0
  - aws-checksums=0.2.0
  - aws-crt-cpp=0.29.0
  - aws-sdk-cpp=1.11.407
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - blinker=1.8.2
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.2
  - ca-certificates=2024.8.30
  - cachetools=5.5.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - comm=0.2.2
  - debugpy=1.8.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - freetype=2.12.1
  - gflags=2.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glog=0.7.1
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=7.2.1
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.29.0
  - ipywidgets=8.1.5
  - jedi=0.19.1
  - jinja2=3.1.4
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.13
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=18.0.0
  - libarrow-acero=18.0.0
  - libarrow-dataset=18.0.0
  - libarrow-substrait=18.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libcxx=19.1.3
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgoogle-cloud=2.30.0
  - libgoogle-cloud-storage=2.30.0
  - libgrpc=1.67.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.28
  - libparquet=18.0.0
  - libpng=1.6.44
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.8.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.13.4
  - libzlib=1.3.1
  - llvm-openmp=19.1.3
  - loguru=0.7.2
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - narwhals=1.13.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.2
  - orc=2.0.2
  - packaging=24.1
  - pandas=2.2.3
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=24.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - protobuf=5.28.2
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=18.0.0
  - pyarrow-core=18.0.0
  - pycparser=2.22
  - pydeck=0.8.0
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.12.7
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rich=13.9.4
  - rpds-py=0.20.1
  - setuptools=75.3.0
  - six=1.16.0
  - smmap=5.0.0
  - snappy=1.2.1
  - stack_data=0.6.2
  - streamlit=1.39.0
  - tenacity=9.0.0
  - tk=8.6.13
  - toml=0.10.2
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - tzlocal=5.2
  - urllib3=2.2.3
  - validators=0.34.0
  - watchdog=4.0.1
  - wcwidth=0.2.13
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zstandard=0.23.0
  - zstd=1.5.6
